#include "A_.h"

namespace A_trans
{
	//translation
	void loadTranslation()
	{
		language_info* lang = translation->add_language("cn", "CN");

		lang->add_translation({
			{translation_hash(" - -  Utility - - "), L" - - 实用工具 - - "},
			{translation_hash("Follow ally mode"), L"跟随队友模式"},
			{translation_hash("Practice Tools"), L"练习工具"},
			{translation_hash("CD item"), L"冷却装备"},
			{translation_hash("Now in Chinese only"), L"目前只有中文"},
			{translation_hash("You need change language to chinese"), L"你需要切换成中文(如果没有，换成英文再换回中文)"},
			{translation_hash("The following plugins are supported"), L"支援以下插件"},
			{translation_hash("Translate"), L"翻译"},
			{translation_hash(" - - Auto level up - - "), L" - - 自动升级 - - "},
			{translation_hash("Auto level up"), L"自动升级"},
			{translation_hash(" - - Priority - - "), L" - - 优先升级 - - "},
			{translation_hash("Priority 1"), L"优先1"},
			{translation_hash("Priority 2"), L"优先2"},
			{translation_hash("Priority 3"), L"优先3"},
			{translation_hash("Priority 3 spell level up to 1"), L"优先3技能升至1"},
			{translation_hash("Use priority"), L"使用优先升级"},
			{translation_hash(" - - Details - - "), L" - - 详细 - - "},
			{translation_hash("Monster selector key"), L"野怪选择快捷键"},
			{translation_hash("Semi smite hero"), L"半手动惩戒英雄"},
			{translation_hash("Auto smite ks"), L"自动惩戒捡人头"},
			{translation_hash(" - - Smite - - "), L" - - 惩戒 - - "},
			{translation_hash(" - - Monster - - "), L" - - 野怪 - - "},
			{translation_hash("  ^- Use smite key"), L"  ^- 使用惩戒快捷键"},
			{translation_hash(" - - Smite Hero - - "), L" - - 惩戒英雄 - - "},
			{translation_hash("Summoner"), L"召唤师技能"},
			{translation_hash("item"), L"装备"},
			{translation_hash(" - - Goredrinker - - "), L" - - 渴血战斧 - - "},
			{translation_hash("Use Goredrinker >= x hero"), L"使用渴血 >= x英雄"},
			{translation_hash("Use Goredrinker <= x% hp"), L"使用渴血 <= x%生命"},
			{translation_hash(" - - Combo - - "), L" - - 连招 - - "},
			{translation_hash(" - - Harass - - "), L" - - 骚扰 - - "},
			{translation_hash("Use Goredrinker harass"), L"使用渴血骚扰"},
			{translation_hash(" - - LaneClear - - "), L" - - 清线 - - "},
			{translation_hash("Use Goredrinker >= x minion"), L"使用渴血 >= x小兵"},
			{translation_hash("Use Goredrinker >= x monster"), L"使用渴血 >= x野怪"},
			{translation_hash(" - - Fast LaneClear - - "), L" - - 快速清线 - - "},
			{translation_hash("Use Goredrinker fast laneclear"), L"使用渴血快速清线"},
			{translation_hash(" - - Auto - - "), L" - - 自动 - - "},
			{translation_hash("Auto Goredrinker >= x hero"), L"自动渴血 >= x英雄"},
			{translation_hash("Gargoyle Stoneplate"), L"石像鬼"},
			{translation_hash(" - - Gargoyle Stoneplate - - "), L" - - 石像鬼 - - "},
			{translation_hash("Use Gargoyle Stoneplate <= x% hp"), L"使用石像鬼 <= x%生命"},
			{translation_hash("Use Gargoyle Stoneplate incoming damage >= x% Gargoyle Stoneplate shield"), L"使用石像鬼来袭伤害 >= x%石像鬼护盾"},
			{translation_hash("  ^- Only <= x % hp"), L" ^~ 只有 <= x%生命"},
			{translation_hash(" - - Warning - - "), L" - - 警告 - - "},
			{translation_hash("  Using this feature may make your teammates AFK  "), L" 开启这个功能可能会导致队友挂机"},
			{translation_hash("Smite siege minion"), L"惩戒炮车"},
			{translation_hash("Force levelup ult"), L"强制升级大招"},
			{translation_hash("Dragon"), L"小龙"},
			{translation_hash("Rift Herald"), L"峡谷先锋"},
			{translation_hash("Small Crab"), L"河蟹"},
			{translation_hash("Red Buff"), L"红buff"},
			{translation_hash("Blue Buff"), L"蓝buff"},
			{translation_hash("Three Wolf"), L"三狼"},
			{translation_hash("Stone"), L"石头"},
			{translation_hash("Six Bird"), L"六鸟"},
			{translation_hash("Gromp"), L"蟾蜍"},
			{translation_hash("Use monster"), L"使用野怪"},
			{translation_hash(" - - Draw State - - "), L" - - 绘制状态 - - "},
			{translation_hash("Draw Farm"), L"绘制发育"},
			{translation_hash("Hero"), L"英雄"},
			{translation_hash("Taric"), L"塔里克(宝石)"},
			{translation_hash("Taric E magnet"), L"塔里克E磁铁"},
			{translation_hash("  ^- Only with combo mode"), L"  ^- 只有连招模式使用"},
			{translation_hash("  ^- E Magnet disable evade"), L"  ^- E磁铁时禁用躲避"},
			{translation_hash("Use smite when enemy <= x range (0 = disable)"), L"敌人 <= x距离才使用惩戒 (0=禁用)"},
			{translation_hash("Draw Smite Range"), L"绘制惩戒范围"},
			{translation_hash("Use Jax E"), L"使用武器E"},
			{translation_hash("Jax"), L"贾克斯(武器)"},
			{translation_hash("Aatrox P"), L"剑魔被动普攻"},
			{translation_hash("Camille Q2"), L"卡蜜儿Q2"},
			{translation_hash("Darius W"), L"诺手W"},
			{translation_hash("Garen Q"), L"盖伦Q"},
			{translation_hash("Monkey Q"), L"猴子Q"},
			{translation_hash("Renekton W"), L"鳄鱼W"},
			{translation_hash("Renekton angry W"), L"鳄鱼生气W"},
			{translation_hash("Volibear Q"), L"狗熊Q"},
			{translation_hash("Twisted Fate W (Gold)"), L"卡牌黄牌"},
			{translation_hash("  ^- Hotkey Smite range"), L"  ^- 热键惩戒范围"},
			{translation_hash(" - - Summoner spell - - "), L" - - 召唤师技能 - - "},
			{translation_hash(" - - Item - - "), L" - - 装备 - - "},
			{translation_hash(" - - Hero - - "), L" - - 英雄 - - "},
			{translation_hash("  ^- Use selector hotkey monster"), L"  ^- 使用野怪选择快捷键"},
			{translation_hash("  ^- Dont use magnet in turret"), L"  ^- 塔下不要使用磁铁"},
			{translation_hash("Cleanse/Qss/Mikael"), L"解控(净化/水银/米凯)"},
			{translation_hash("Mikael"), L"米凯"},
			{translation_hash("Qss"), L"水银"},
			{translation_hash("Danger level setting"), L"危险等级设置"},
			{translation_hash(" - - Danger Level - - "), L" - - 危险等级 - - "},
			{translation_hash("Danger level 0"), L"危险等级0"},
			{translation_hash("Danger level 1"), L"危险等级1"},
			{translation_hash("Danger level 2"), L"危险等级2"},
			{translation_hash("Danger level 3"), L"危险等级3"},
			{translation_hash("Danger level 4"), L"危险等级4"},
			{translation_hash("Alway use"), L"总是使用"},
			{translation_hash("Delay x ms"), L"延迟x毫秒"},
			{translation_hash("Hp <= x %"), L"生命 <= x%"},
			{translation_hash("When x range"), L"x范围内"},
			{translation_hash("  ^- >= x enemy"), L"  ^- >= x敌人"},
			{translation_hash("CC duration >= x ms"), L"控制持续时间 >= x毫秒"},
			{translation_hash("Use on combo mode"), L"用于连招模式"},
			{translation_hash("Use on harass mode"), L"用于骚扰模式"},
			{translation_hash("Use on other mode"), L"用于其它模式"},
			{translation_hash("Danger level 0 = Disable"), L"危险等级0 = 禁用"},
			{translation_hash(" - - Setting - - "), L" - - 设置 - - "},
			{translation_hash(" - - Mikael - - "), L" - - 米凯 - - "},
			{translation_hash("Mikael use on"), L"米凯用于"},
			{translation_hash(" - - Mikael setting - - "), L" - - 米凯设置 - - "},
			{translation_hash("Danger level : Berserk"), L"危险等级：狂暴"},
			{translation_hash("Danger level : Stun"), L"危险等级：晕眩"},
			{translation_hash("Danger level : Taunt"), L"危险等级：嘲讽"},
			{translation_hash("Danger level : Polymorph"), L"危险等级：变形"},
			{translation_hash("Danger level : Fear"), L"危险等级：恐惧"},
			{translation_hash("Danger level : Charm"), L"危险等级：魅惑"},
			{translation_hash("Danger level : Drowsy"), L"危险等级：困倦"},
			{translation_hash("Danger level : Asleep"), L"危险等级：睡着"},
			{translation_hash("Danger level : Snare"), L"危险等级：禁锢"},
			{translation_hash("Danger level : Slow"), L"危险等级：减速"},
			{translation_hash("Danger level : Silence"), L"危险等级：沉默"},
			{translation_hash("Danger level : Exhaust"), L"危险等级：虚弱" },
			{translation_hash("Danger level : Ignite"), L"危险等级：点火" },
			{translation_hash("Danger level : Blind"), L"危险等级：致盲"},
			{translation_hash("Danger level : Disarm"), L"危险等级：缴械"},
			{translation_hash("Danger level : NearSight"), L"危险等级：近视"},
			{translation_hash("Danger level : Suppression"), L"危险等级：压制"},
			{translation_hash(" - - Qss - - "), L" - - 水银 - - "},
			{translation_hash(" - - Qss setting - - "), L" - - 水银设置 - - "},
			{translation_hash(" - - Cleanse - - "), L" - - 净化 - - "},
			{translation_hash(" - - Cleanse setting - - "), L" - - 净化设置 - - "},
			{translation_hash("Ironspike"), L"铁刺鞭"},
			{translation_hash(" - - Ironspike - - "), L" - - 铁刺鞭 - - "},
			{translation_hash("Use ironspike combo"), L"使用铁刺鞭连招"},
			{translation_hash("Use ironspike harass"), L"使用铁刺鞭骚扰"},
			{translation_hash("Use ironspike >= x minion"), L"使用铁刺鞭 >= x小兵"},
			{translation_hash("Use ironspike >= x monster"), L"使用铁刺鞭 >= x野怪"},
			{translation_hash("Use ironspike fast laneclear"), L"使用铁刺鞭快速清线"},
			{translation_hash("Use stridebreaker >= x hero"), L"使用挺进 >= x敌人"},
			{translation_hash("Use stridebreaker harass"), L"使用挺进骚扰"},
			{translation_hash("Use stridebreaker >= x minion"), L"使用挺进 >= x小兵"},
			{translation_hash("Use stridebreaker >= x monster"), L"使用挺进 >= x野怪"},
			{translation_hash("Use stridebreaker fast laneclear"), L"使用挺进快速清线"},
			{translation_hash(" - - Auto use on - - "), L" - - 自动用于 - - "},
			{translation_hash("Randuins"), L"兰盾"},
			{translation_hash(" - - Randuins - - "), L" - - 兰盾 - - "},
			{translation_hash("PracticeTool_TargetDummy"), L"假人"},
			{translation_hash("Wenrou"), L"温柔"},
			{translation_hash("Use ironspike >= x minion (after aa)"), L"使用铁刺鞭 >= x小兵 (普攻后)"},
			{translation_hash("Use ironspike >= x monster (after aa)"), L"使用铁刺鞭 >= x野怪 (普攻后)"},
			{translation_hash("Use stridebreaker >= x minion (after aa)"), L"使用挺进 >= x小兵 (普攻后)"},
			{translation_hash("Use stridebreaker >= x monster (after aa)"), L"使用挺进 >= x野怪 (普攻后)"},
			{translation_hash("Use Goredrinker >= x minion (after aa)"), L"使用渴血 >= x小兵 (普攻后)" },
			{translation_hash("Use Goredrinker >= x monster (after aa)"), L"使用渴血 >= x野怪 (普攻后)" },
			{translation_hash("Force attack heartsteel enemy"), L"强制攻击有心之钢的敌人"},
			{translation_hash("Draw heartsteel state"), L"绘制心之钢状态"},
			{translation_hash("Heartsteel"), L"心之钢"},
			{translation_hash(" - - Heartsteel - - "), L" - - 心之钢 - - "},
			{translation_hash("Information"), L"脚本资讯" },
			{translation_hash(" - - Chat - - "), L" - - 聊天 - - "},
			{translation_hash("Chat"), L"聊天"},
			{translation_hash(" - - Xayah - - "), L" - - 霞 - - "},
			{translation_hash("Draw Xayah E"), L"绘制霞的E"},
			{translation_hash("Thresh"), L"锤石"},
			{translation_hash(" - - Thresh - - "), L" - - 锤石 - - "},
			{translation_hash("Use lantern"), L"使用灯笼"},
			{translation_hash("Use lantern range"), L"使用灯笼范围"},
			{translation_hash("Ward enemy lantern"), L"敌人灯笼放眼"},
			{translation_hash("Cassiopeia/Tryndamere"), L"蛇女/蛮王"},
			{translation_hash(" - - Cassiopeia and Tryndamere are couples - - "), L" - - 蛇女/蛮王 - - "},
			{translation_hash("Dodge Cassiopeia R / Tryndamere W"), L"躲蛇女R蛮王W"},
			{translation_hash(" - - Jax - - "), L" - - 武器 - - "},
			{translation_hash("Ignite"), L"点火"},
			{translation_hash(" - - Exhaust - - "), L" - - 虚弱 - - "},
			{translation_hash("Use semi exhaust"), L"半手动虚弱"},
			{translation_hash("Type"), L"种类"},
			{translation_hash("Close to me"), L"靠近自己"},
			{translation_hash("Close to mouse"), L"靠近鼠标"},
			{translation_hash(" - - Use to - - "), L" - - 用于 - - "},
			{translation_hash("Twitch's E >= x"), L"老鼠E >= x"},
			{translation_hash("Xayah's E >= x"), L"霞E >= x"},
			{translation_hash(" - - Ignite - - "), L" - - 点火 - - "},
			{translation_hash("Use semi ignite"), L"半手动点火"},
			{translation_hash("Dont over kill"), L"不要过度击杀"},
			{translation_hash("Use in other mode"), L"用于其它模式"},
			{translation_hash("Use if enemy x range"), L"敌人在x范围内时使用"},
			{translation_hash("  ^- ally <= x"), L"  ^-友军 <= x"},
			{translation_hash(" - - Heal - - "), L" - - 治疗术 - - "},
			{translation_hash(" - - Myhero - - "), L" - - 我 - - "},
			{translation_hash(" - - Ally - - "), L" - - 友军 - - "},
			{translation_hash("HP <= x%"), L"生命 <= x%"},
			{translation_hash("Incoming damage HP <= x%"), L"生命 - 来袭伤害 <= x%"},
			{translation_hash("Level > x"), L"等级 > x"},
			{translation_hash("Use if x range"), L"在x范围内时使用"},
			{translation_hash("  ^- enemy >= x"), L"  ^- 敌人 >= x"},
			{translation_hash("Dont use heal if dmg > hp + heal"), L"伤害 > 生命 + 治疗时不要使用"},
			{translation_hash("Barrier"), L"光盾"},
			{translation_hash(" - - Barrier - - "), L" - - 光盾 - - "},
			{translation_hash("Dont use barrier if dmg > hp + heal"), L"伤害 > 生命 + 光盾时不要使用"},
			{translation_hash("Show all"), L"显示全部"},
			{translation_hash("Health Potion"), L"药水"},
			{translation_hash(" - - Health Potion - - "), L" - - 药水 - - "},
			{translation_hash("Use Health Potion"), L"使用生命药水"},
			{translation_hash("Use in combo"), L"连招模式下使用"},
			{translation_hash("Refillable Potion"), L"复用型药水"},
			{translation_hash(" - - Refillable Potion - - "), L" - - 复用型药水 - - "},
			{translation_hash("Corrupting Potion"), L"腐败药水"},
			{translation_hash(" - - Corrupting Potion - - "), L" - - 腐败药水 - - "},
			{translation_hash("Biscuit"), L"饼干"},
			{translation_hash(" - - Biscuit - - "), L" - - 饼干 - - "},
			{translation_hash("Use Biscuit"), L"使用饼干"},
			{translation_hash("Use Corrupting Potion"), L"使用腐败药水"},
			{translation_hash("Use Refillable Potion"), L"使用复用型药水"},
			{translation_hash("Draw ward range"), L"显示眼睛范围"},
			{translation_hash("Draw ward"), L"显示眼睛"},
			{translation_hash(" - - Ward - - "), L" - - 眼睛 - - "},
			{translation_hash("  ^- Disable Orbwalker -> Misc -> Attack object -> Attack plants"), L"  ^- 关闭 走砍->杂项->攻击目标设置->攻击植物"},
			{translation_hash(" - - Misc - - "), L" - - 杂项 - - "},
			{translation_hash(" - - Orbwalker - - "), L" - - 走砍 - - "},
			{translation_hash("Only fast laneclear hit plant"), L"只有快速清线时攻击植物"},
			{translation_hash(" - - Flash - - "), L" - - 闪现 - - "},
			{translation_hash("Flash anti gapcloser"), L"闪现反突进"},
			{translation_hash("Enemy close me <= x range"), L"敌人距离我 <= x"},
			{translation_hash(" - - Anti Gapcloser to - - "), L" - - 反突进于 - - "},
			{translation_hash("Hp <= x%"), L"生命 <= x%"},
			{translation_hash("Snowball"), L"雪球"},
			{translation_hash(" - - Snowball - - "), L" - - 雪球 - - "},
			{translation_hash("Semi snowball"), L"半手动雪球"},
			{translation_hash("Use range"), L"使用范围"},
			{translation_hash(" - - Info - - "), L" - - 资讯 - - "},
			{translation_hash("Version"), L"版本"},
			{translation_hash("Important tips"), L"重要提示"},
			{translation_hash("Use Chinese"), L"使用中文"},
			{translation_hash("Info"), L"资讯"},
			{translation_hash("Use smite key"), L"使用惩戒"},
			{translation_hash("Smite mode"), L"惩戒模式"},
			{translation_hash("Custom"), L"自定"},
			{translation_hash("Have enemy"), L"有敌人时"},
			{translation_hash("Semi smite enemy"), L"半手动惩戒敌人"},
			{translation_hash("Draw smite range (100 = Disable)"), L"绘制惩戒范围(100 = 关闭)"},
			{translation_hash("Glow inside size"), L"荧光内大小" },
			{translation_hash("Glow inside power"), L"荧光内强度" },
			{translation_hash("Glow outside size"), L"荧光外大小" },
			{translation_hash("Glow outside power"), L"荧光外强度" },
			{translation_hash("Draw smite state"), L"绘制惩戒状态"},
			{translation_hash(" - - Draw - - "), L" - - 绘制 - - "},
			{translation_hash("Semi smite monster(can kill)"), L"半手动惩戒野怪(可击杀)"},
			{translation_hash("Save smite (?)"), L"保存惩戒 (?)"},
			{translation_hash("Save smite if any epic is alive or about to spawn"), L"保存惩戒如果史诗级也怪即将出生"},
			{translation_hash("Melee Magnet"), L"近战磁铁"},
			{translation_hash("Key"), L"热键"},
			{translation_hash("Credit : Chase (1v9)"), L"1V9协助制作"},
			{translation_hash("Chat setting"), L"聊天设置"},
			{translation_hash(" - - Magnet - - "), L" - - 磁铁 - - "},
			{translation_hash("Text"), L"文本"},
			{translation_hash(" - - Text - - "), L" - - 文本 - - "},
			{translation_hash("Use text"), L"使用文本"},
			{translation_hash("Word       "), L"文字       "},
			{translation_hash("Monster tracker"), L"追踪野怪"},
			{translation_hash(" - - Monster tracker - - "), L" - - 追踪野怪 - - "},
			{translation_hash("Use monster tracker"), L"使用追踪野怪"},
			{translation_hash("Show all spell"), L"显示所有技能"},
			{translation_hash("Ghost"), L"疾跑"},
			{translation_hash(" - - Ghost - - "), L" - - 疾跑 - - "},
			{translation_hash(" - - Chase logic - - "), L" - - 追击逻辑 - - "},
			{translation_hash("Chase"), L"追击"},
			{translation_hash("  ^- logic (?)"), L"  ^-可莉逻辑 (?)"},
			{translation_hash("Avoiding waste ghost"), L"避免浪费疾跑"},
			{translation_hash("  ^-Enemy HP >= x%"), L"  ^-敌人生命 >= x%"},
			{translation_hash("  ^-Enemy HP <= x%"), L"  ^-敌人生命 <= x%"},
			{translation_hash("  ^-Mouse distance <= x%"), L"  ^-鼠标距离 <= x%"},
			{translation_hash("  ^-Enemy distance <= AA range + x"), L"  ^-敌人距离 <= aa范围 + x"},
			{translation_hash("Chase to"), L"追击于"},
			{translation_hash(" - - Flee logic - - "), L" - - 逃跑逻辑 - - "},
			{translation_hash("  ^-HP <= x%"), L"  ^-生命 <= x%"},
			{translation_hash("Flee to"), L"对...逃跑"},
			{translation_hash("Anti Flash"), L"闪现反闪现突进"},
			{translation_hash("Snow ball"), L"雪球"},
			{translation_hash("Enemy hp <= x"), L"敌人生命 <= x%"},
			{translation_hash("Show all hero"), L"显示所有英雄"},
			{translation_hash("Use summoner spell"), L"使用召唤师技能"},
			{translation_hash("Interval ( s )"), L"间隔(秒)"},
			{translation_hash("Elements"), L"构成要素"},
			{translation_hash("Count per interval"), L"间隔计数"},
			{translation_hash("Peak"), L"最高值"},
			{translation_hash("Average"), L"平均值"},
			{translation_hash(" - - Spell - - "), L" - - 技能 - - "},
			{translation_hash("QWER spells"), L"QWER 技能"},
			{translation_hash("Summoner spells"), L"召唤师技能"},
			{translation_hash("XP bar"), L"经验条"},
			{translation_hash(" - - Items - - "), L" - - 道具 - - "},
			{translation_hash("Active item"), L"主动装备"},
			{translation_hash("Stasis item"), L"秒表装备"},
			{translation_hash("Cleanse item"), L"水银装备"},
			{translation_hash("Shield item"), L"护盾装备"},
			{translation_hash("Yuumi's QWE"), L"悠咪QWE"},
			{translation_hash("Yuumi's R"), L"悠咪大招"},
			{translation_hash("Yuumi's Summoners"), L"悠咪召唤师技能"},
			{translation_hash(" - - Whitelist - - "), L" - - 白名单 - - "},
			{translation_hash("Allies"), L"队友"},
			{translation_hash("Enemies"), L"敌人"},
			{translation_hash(" - - Colors - - "), L" - - 颜色 - - "},
			{translation_hash("Color 1"), L"颜色1"},
			{translation_hash("Color 2"), L"颜色2"},
			{translation_hash("Restore default"), L"恢复预设"},
			{translation_hash("Spells text size"), L"技能文字大小"},
			{translation_hash("XP bar Y offset"), L"经验条y偏移" },
			{translation_hash("XP bar size"), L"经验条大小"},
			{translation_hash("Spells Y offset"), L"技能y偏移" },
			{translation_hash("HP bar X offset"), L"生命条x偏移" },
			{translation_hash("HP bar Y offset"), L"生命条y偏移"},
			{translation_hash("HP bar width offset / 1000"), L"生命条宽度偏移"},
			{translation_hash("HP bar height offset / 1000"), L"生命条高度偏移"},
			{translation_hash("Sizes"), L"大小"},
			{translation_hash(" - - Common - - "), L" - - 一般 - - "},
			{translation_hash("Delay (ms)"), L"延迟(毫秒)"},
			{translation_hash("Level-up R"), L"升R"},
			{translation_hash("Level-up QWE"), L"升QWE"},
			{translation_hash(" - - Priorities - - "), L" - - 优先 - - "},
			{translation_hash("Level 1-3"), L"1-3等"},
			{translation_hash(" - - Presets manager - - "), L" - - 预设选择 - - "},
			{translation_hash("Preset name"), L"预设名称"},
			{translation_hash("jungle"), L"打野"},
			{translation_hash("support"), L"辅助"},
			{translation_hash("toplane"), L"上单"},
			{translation_hash("midlane"), L"中单"},
			{translation_hash("custom1"), L"自定义1"},
			{translation_hash("custom2"), L"自定义2"},
			{translation_hash("custom3"), L"自定义3"},
			{translation_hash("Auto leveler"), L"自动升等"},
			{translation_hash(" - - Smite Siege Minion (?) - - "), L" - - 惩戒炮车 (?) - - "},
			{translation_hash("Selector position"), L"选择位置"},
			{translation_hash("Monster whitelist"), L"野怪白名单"},
			{translation_hash("  Using this feature may make your teammates AFK  "), L"这个可能会让你的队友挂机"},
			{translation_hash("Objective"), L"史诗野怪"},
			{translation_hash("Scuttle Crab"), L"峡谷先锋"},
			{translation_hash("Blue/Red Buff"), L"红蓝buff"},
			{translation_hash("Murkwolf"), L"三狼"},
			{translation_hash("Krug"), L"石头"},
			{translation_hash("Raptor"), L"六鸟"},
			{translation_hash("Gromp"), L"蟾蜍"},
			{translation_hash("Monster"), L"野怪"},
			{translation_hash("Camp"), L"营地"},
			{translation_hash("Draw smite damage"), L"绘制惩戒伤害"},
			{translation_hash("Show permanently"), L"永久显示"},
			{translation_hash("Gold tracker"), L"金币追踪"},
			{translation_hash(" - - Script tracker (?) - - "), L" - - 脚本追踪 (?) - - "},
			{translation_hash("Can be used to estimate if someone is scripting"), L"数字越大越有可能是脚本"},
			{translation_hash("Draw setting"), L"绘制设置"},
			{translation_hash("Disable outline"), L"禁用编框"},
			{translation_hash(" - - Size - - "), L" - - 大小 - - "},
			{translation_hash("Show FF"), L"显示投降"},
			{translation_hash(" - - Show FF - - "), L" - - 显示投降 - - "},
			{translation_hash("Auto rundown"), L"自动送头"},
			{translation_hash(" - - I want got ban - - "), L" - - 我想被锁账号 - - "},
			{translation_hash("Animate color"), L"使用动画"},
			{translation_hash("jungle (can't modify)"), L"打野 (无法修改)"},
			{translation_hash("support (can't modify)"), L"辅助 (无法修改)"},
			{translation_hash("adc (can't modify)"), L"射手 (无法修改)"},
			{translation_hash("toplane (can't modify)"), L"上单 (无法修改)"},
			{translation_hash("midlane (can't modify)"), L"中单 (无法修改)"},
			{translation_hash("Kayn"), L"凯影"},
			{translation_hash(" - - Kayn - - "), L" - - 凯影 - - "},
			{translation_hash("Draw Kayn E"), L"绘制凯影E"},
			{translation_hash("Ward"), L"眼睛"},
			{translation_hash("Draw ward range ally"), L"绘制队友眼睛范围"},
			{translation_hash(" - - Trick spots - - "), L" - - 眼位 - - "},
			{translation_hash("Ward cast assist"), L"插眼辅助"},
			{translation_hash("Warwick Q"), L"狼人Q"},
			{translation_hash("Leona Q"), L"日女Q"},
			{translation_hash("Trundle Q"), L"巨魔Q"},
			{translation_hash("Udyr E"), L"乌迪尔E"},
			{translation_hash("Alistar E"), L"牛E"},
			{translation_hash("Blitzcrank E"), L"机器人E"},
			{translation_hash("Sona E"), L"索娜E"},
			{translation_hash("Xinzhao Q3"), L"赵信Q3"},
			{translation_hash("Zac Q"), L"札克Q"},
			{translation_hash("Level 1-5"), L"1-5等"},
			{translation_hash("Level 6+"), L"6等后"},
			{translation_hash("Tracker"), L"追踪器"},
			{translation_hash(" - - Tracker - - "), L" - - 追踪器 - - "},
			{translation_hash("Tracker List"), L"追踪器名单"},
			{translation_hash("Script Tracker"), L"脚本追踪"},
			{translation_hash("Item Tracker"), L"装备追踪"},
			{translation_hash(" - - Settings - - "), L" - - 设置 - - "},
			{translation_hash("Hide for visible heroes"), L"隐藏可见的英雄"},
			{translation_hash("Ally path"), L"队友路径"},
			{translation_hash("Enemy path"), L"敌人路径"},
			{translation_hash("Outline leveled spells"), L"绘制已学习技能边框"},
			{translation_hash("Outline unleveled spells"), L"绘制未学习技能边"},
			{translation_hash(" - - Move - - "), L" - - 移动 - - "},
			{translation_hash("Min delay ( ms )"), L"最小延迟 (毫秒)"},
			{translation_hash("Max delay ( ms )"), L"最大延迟 (毫秒)"},
			{translation_hash(" - - Attack - - "), L" - - 攻击 - - "},
			{translation_hash("Extra randomize range"), L"额外随机范围"},
			{translation_hash("Fake cursor (Beta)"), L"虚假光标 (测试版)"},
			{translation_hash("Draw ward time"), L"绘制视野时间"},
			{translation_hash(" - - Auto buy - - "), L" - - 自动购买 - - "},
			{translation_hash("Auto buy other ward"), L"自动购买其他眼睛"},
			{translation_hash("Oracle Lens"), L"扫眼"},
			{translation_hash("Farsight Alteration"), L"蓝眼"},
			{translation_hash(" ^- Level >= x"), L" ^- 等级 >= x"},
			{translation_hash("Path tracker"), L"路径追踪"},
			{translation_hash(" - - Katarina - - "), L" - - 卡特 - - "},
			{translation_hash("Draw Dagger"), L"绘制匕首"},
			{translation_hash(" - - Yasuo - - "), L" - - 亚索 - - "},
			{translation_hash("Draw Yasuo E"), L"绘制亚索E"},
			{translation_hash(" - - Cassiopeia and Tryndamere - - "), L" - - 蛇女和蛮王 - - "},
			{translation_hash("Show emote/master after kill"), L"击杀后秀专精/表情"},
			{translation_hash("Show master"), L"秀专精"},
			{translation_hash("Show Emote Type"), L"秀表情"},
			{translation_hash("Top"), L"上"},
			{translation_hash("Top Right"), L"右上"},
			{translation_hash("Right"), L"右"},
			{translation_hash("Right Down"), L"右下"},
			{translation_hash("Down"), L"下"},
			{translation_hash("Left Down"), L"左下"},
			{translation_hash("Left"), L"左"},
			{translation_hash("Top Left"), L"左上"},
			{translation_hash("Mid"), L"中间"},
			{translation_hash("Show turret"), L"显示防御塔"},
			{translation_hash(" - - Show turret - - "), L" - - 显示防御塔 - - "},
			{translation_hash("Show turret distance (1499 = Disable)"), L"显示防御塔距离 (1499 = 禁用)"},
			{translation_hash("Auto buy other ward (Sup)"), L""},
			{translation_hash("Show turret distance"), L"显示防御塔范围"},
			{translation_hash("Turret hit me range"), L"防御塔攻击我范围"},
			{translation_hash("Turret hit me"), L"防御塔打我"},
			{translation_hash("Turret AFK range"), L"防御塔不攻击范围"},
			{translation_hash("Turret AFK"), L"防御塔不攻击"},
			{translation_hash("Turret hit other range"), L"防御塔打别人范围"},
			{translation_hash("Turret hit other"), L"防御塔打别人"},
			{translation_hash("Emote/mastery/dance/movement"), L"表情/专精/互动"},
			{translation_hash(" - - On kill - - "), L" - - 击杀时 - - "},
			{translation_hash("Show mastery"), L"秀专精"},
			{translation_hash("Emote spam key"), L"互动键"},
			{translation_hash("Dance"), L"跳舞"},
			{translation_hash("Laugh"), L"大笑"},
			{translation_hash("Joke"), L"讲笑话"},
			{translation_hash("Toggle"), L"切换(例如剑魔)"},
			{translation_hash("Next mode"), L"下一个模式"},
			{translation_hash("Watermark"), L"浮水印"},
			{translation_hash( "Draw Watermark" ), L"绘制浮水印" },
			{translation_hash(" - - Watermark - - "), L" - - 浮水印 - - "},
			{translation_hash("Animate alpha"), L"动画透明度"},
			{translation_hash("Show ally turret range"), L"显示友军防御塔范围"},
			{translation_hash("Enemy turret distance"), L"敌人防御塔范围"},
			{translation_hash("Ally turret distance"), L"友军防御塔范围"},
			{translation_hash(" - - Plates - - "), L" - - 塔皮 - - "},
			{translation_hash("Plates remaining time ally"), L"友军塔皮剩余时间"},
			{translation_hash("Plates remaining time enemy"), L"敌军塔皮剩余时间"},
			{translation_hash("Animations"), L"使用动画"},
			{translation_hash("Draw inside"), L"绘制内部"},
			{translation_hash(" - - Colors ally - - "), L" - - 友军颜色 - - "},
			{translation_hash("Ally turret range"), L"友军防御塔范围"},
			{translation_hash("Ally plates color"), L"友军塔皮颜色"},
			{translation_hash(" - - Colors enemy - - "), L" - - 敌军颜色 - - "},
			{translation_hash("Enemy plates color"), L"敌军塔皮颜色"},
			{translation_hash("Show inhibitor"), L"显示兵营"},
			{translation_hash("Show ally inhibitor respawn time"), L"显示友军兵营时间"},
			{translation_hash("Show enemy inhibitor respawn time"), L"显示敌军兵营时间"},
			{translation_hash("Ally color"), L"友军颜色"},
			{translation_hash("Enemy color"), L"敌军颜色"},
			{translation_hash("Ranges"), L"范围"},
			{translation_hash("Draw ranges"), L"绘制范围"},
			{translation_hash("New draw"), L"新绘制"},
			{translation_hash("Arc angle (?)"), L"弧形角度 (?)"},
			{translation_hash("0 = dynamic"), L"0 = 动态"},
			{translation_hash(" - - Show inhibitor - - "), L" - - 显示兵营 - - "},
			{translation_hash("Clone Tracker"), L"克隆追踪"},
			{translation_hash(" - - Clone Tracker - - "), L" - - 克隆追踪 - - "},
			{translation_hash("Draw real"), L"绘制真实"},
			{translation_hash("Draw clone"), L"绘制克隆"},
			{translation_hash("Animation"), L"动画"},
			{translation_hash("Real color"), L"真实颜色"},
			{translation_hash("Fake color"), L"克隆颜色"},
			{translation_hash("Spell HUD"), L"绘制显示器"},
			{translation_hash("Disabled"), L"禁用"},
			{translation_hash("Tracker whitelist"), L"追踪白名单"},
			{translation_hash("FoW Tracker"), L"无视野追踪"},
			{translation_hash("Minimap"), L"小地图"},
			{translation_hash("Save smite if any epic is alive or about to spawn ( don't smite monster )"), L"有史诗野怪时保存惩戒"},
			{translation_hash("Use prediction"), L"使用预判"},
			{translation_hash("Siege minion"), L"炮兵"},
			{translation_hash("Save smite ks (?)"), L"保存惩戒捡人头 (?)"},
			{translation_hash("Save smite if any epic is alive or about to spawn ( don't killsteal on enemy hero )"), L"有史诗野怪时保存惩戒"},
			{translation_hash("Range style"), L"绘制模式"},
			{translation_hash("Circle"), L"圆形"},
			{translation_hash("Corner box"), L"框框"},
			{translation_hash(" - - Auto warding - - "), L" - - 自动插眼 - - "},
			{translation_hash("Auto warding"), L"自动插眼"},
			{translation_hash("Disabled"), L"禁用"},
			{translation_hash("Suggested"), L"推荐"},
			{translation_hash("All "), L"全部"},
			{translation_hash("Use control ward"), L"使用红眼"},
			{translation_hash("Use stealth ward"), L"使用黄眼"},
			{translation_hash("Monsters"), L"野怪"},
			{translation_hash("Small monsters"), L"小怪"},
			{translation_hash(" - - Extra - - "), L" - - 额外 - - "},
			{translation_hash("Draw R spell"), L"绘制R技能"},
			{translation_hash("Icon"), L"图标"},
			{translation_hash("Draw summoner spells"), L"绘制召唤师技能"},
			{translation_hash("Health-based hp color"), L"生命基底颜色"},
			{translation_hash("R color"), L"R颜色"},
			{translation_hash("Icon size monster"), L"野怪图标大小"},
			{translation_hash("Icon size"), L"图标大小"},
			{translation_hash("Summoners colors"), L"召唤师颜色"},
			{translation_hash("Health color"), L"生命颜色"},
			{ translation_hash( "Arc color" ), L"弧颜色" },
			{ translation_hash( "Duration ( s )" ), L"持续时间 ( 秒 )" },
			{ translation_hash( " - - Colors spells - - " ), L" - - 技能颜色 - - " },
			{ translation_hash( "Default color" ), L"默认颜色" },
			{ translation_hash( "Flash color" ), L"闪现颜色" },
			{ translation_hash( "Ghost color" ), L"疾跑颜色" },
			{ translation_hash( "Ignite color" ), L"点火颜色" },
			{ translation_hash( "Smite color" ), L"惩戒颜色" },
			{ translation_hash( "Cleanse color" ), L"净化颜色" },
			{ translation_hash( "Exhaust color" ), L"虚弱颜色" },
			{ translation_hash( "Heal color" ), L"治疗颜色" },
			{ translation_hash( "Barrier color" ), L"光盾颜色" },
			{ translation_hash( "Snowball color" ), L"雪球颜色" },
			//{translation_hash(""), L""},
			//{translation_hash(""), L""},
			//{translation_hash(""), L""},
			//{translation_hash(""), L""},
			//{translation_hash(""), L""},
			//{translation_hash(""), L""},

			//EVADE下面
			{translation_hash("Evade"), L"躲避"},
			{translation_hash("Advanced settings"), L"高级躲避设置"},
			{translation_hash("Restore config"), L"恢复预设"},
			{translation_hash("SummonerSnowball"), L"大乱斗雪球"},
			{translation_hash("Dodge Circular Spells"), L"躲避圆形技能"},
			{translation_hash("Evading settings"), L"躲避设置"},
			{translation_hash("Under tower settings"), L"塔下躲避设置"},
			{translation_hash("Disable dodging under enemy turret"), L"如果在敌方塔下则关闭躲避"},
			{translation_hash("Block moving back into skillshot even if disabled"), L"不会返回到敌方技能的位置"},
			{translation_hash("Max danger level to disable under turret"), L"不在敌方塔下躲避当危险等级 <= x"},
			{translation_hash("Dodge away from enemies"), L"躲避时远离敌方英雄"},
			{translation_hash("Dodge away from enemies distance buffer"), L"躲避时远离敌方英雄的距离加成"},
			{translation_hash("Allow to change path while evading"), L"躲避时可以改变躲避路径"},
			{translation_hash("Max distance of evade point generator"), L"躲避时最远移动距离"},
			{translation_hash("Humanizer settings"), L"人性化躲避设置"},
			{translation_hash("Disable dodging skillshots from FoW"), L"禁用无视野躲避(有时无效)"},
			{translation_hash("Max angle to dodge"), L"躲避允许移动的最大角度"},
			{translation_hash("Spell detection delay"), L"躲避技能延迟(越高躲避反应就越慢)"},
			{translation_hash("Disable during recall"), L"回城时关闭躲避"},
			{translation_hash("Enable Double Click to remove"), L"双击取消躲避"},
			{translation_hash("Allow auto-attack killable Enemy in skillshot"), L"一下平A可击杀则不躲避"},
			{translation_hash("Draw Evade Polygon"), L"躲避轮廓"},
			{translation_hash("Ally shielding"), L"给队友上盾" },

			//BGX
			{ translation_hash("Shaders"), L"绘制(材质)" },
			{ translation_hash("Enable shader drawings for circles and lines"), L"新型绘制套用圆形和线条" },
			{ translation_hash("Enable depth for shaders"), L"新型绘制新增深度" },
			{ translation_hash("Enable height scale for circles"), L"原型绘制使用高度" },



			//kiri's Recall Kill
			{translation_hash("kiri's Recall Kill"), L"Kiri回城大招"},
			{translation_hash("Wait for the last sec."), L"等到能击杀的最后一秒再使用"},
			{translation_hash("Draw status"), L"显示回城击杀开启状态"},
			{translation_hash("Disable key"), L"关闭回城大招"},

			//实用工具
			{translation_hash("QSS/Cleanse"), L"水银和净化"},
			{translation_hash("Cleanse delay(ms)"), L"自动使用净化的延迟"},
			{translation_hash("Mikael ally list"), L"对队友使用坩埚"},
			{translation_hash("Smite"), L"惩戒"},
			{translation_hash("Redemption"), L"救赎"},
			{translation_hash("Redemption max range"), L"救赎最大范围"},
			{translation_hash("Use Redemption"), L"使用救赎"},
			{translation_hash("Juke Revealer"), L"追踪敌人隐身/位移 例如小丑Q，EZ E"},
			{translation_hash("Delay"), L"延迟"},
			{translation_hash("Auto ward"), L"自动插眼"},
			{translation_hash("Auto Orcle's Lens"), L"自动开扫描"},
			{translation_hash("Draws only"), L"只开插眼范围"},
			{translation_hash("Popularity (in % between min, max)"), L"眼位活跃度最佳位置"},
			{translation_hash("Score(in % between min, max"), L"眼位得分最佳位置"},
			{translation_hash("Key (place best possible)"), L"热键自动插眼"},

			//OpenUtilities
			{translation_hash("OpenUtility"), L"Open活化剂"},
			{translation_hash("Teleport"), L"传送"},
			{translation_hash("Show teleport location"), L"现实传送位置"},
			{translation_hash("Epic monster tracker"), L"追踪大型野怪位置"},
			{translation_hash("Show attacked epic monsters notifications"), L"当大型野怪被攻击时显示提示"},
			{translation_hash("Show attacked epic monsters on minimap"), L"当大型也怪呗攻击时在小地图上提示"},
			{translation_hash("Track even if visible"), L"即便能直接看到也要追踪位置"},
			{translation_hash("Notifications horizontal position"), L"显示提示的水平距离"},
			{translation_hash("Notifications vertical position"), L"显示提示的垂直距离"},
			{translation_hash("Distance between notifications"), L"2个提示窗口之间的距离"},
			{translation_hash("Flash utility"), L"特殊闪现设置"},
			{translation_hash("prevent glitching flash in wall"), L"防止bug闪现撞墙"},
			{translation_hash("Auto extend flash"), L"自动延长闪现距离"},
			{translation_hash("Anti nexus turret"), L"防御塔设定"},
			{translation_hash("Avoid going under Nexus turret"), L"防止英雄走到敌方防御塔下"},
			{translation_hash("Draw owner name"), L"写出名字"},
			{translation_hash("Auto ping wards"), L"自动ping眼"},
			{translation_hash("Only ping if visible"), L"只会在眼能被所有人看到的时候ping"},
			{translation_hash("Only ping if valid"), L"没用的功能"},
			{translation_hash("Low spec mode (tick limiter)"), L"没用的功能"},
			{translation_hash("Debug print in console (dev)"), L"没用的功能"},

			//视觉效果
			{translation_hash("Hide drawings in obs/discord"), L"直播模式/在discord或者obs上不显示所有线圈"},
			{translation_hash("Game visuals"), L"无限视距和防御塔范围"},
			{translation_hash("Camera height （zoomhack)"), L"无限视距(拉到0是关闭)"},
			{translation_hash("Summoner name changer"), L"改变显示的召唤师名字"},
			{translation_hash("My name"), L"我的名字是"},
			{translation_hash("Ally names"), L"队友的名字"},
			{translation_hash("Enemy names"), L"敌人的名字"},
			{translation_hash("Apply changes"), L"应用改动"},
			{translation_hash("BGX banners"), L"没用的功能"},

			//BGX changer
			{translation_hash("BGX Changer"), L"换皮肤"},
			{translation_hash("Champion skins"), L"换英雄皮肤"},
			{translation_hash("Minions skins"), L"换小兵皮肤"},
			{translation_hash("My ward"), L"换眼的皮肤"},
			{translation_hash("Minions skin"), L"换小兵的皮肤"},
			{translation_hash("Baron"), L"大龙"},
			{translation_hash("Blue"), L"换蓝buff的皮肤"},
			{translation_hash("Red"), L"换红buff的皮肤"},
			{translation_hash("Crab"), L"换河蟹皮肤"},
			{translation_hash("Razorbeak"), L"换F6皮肤"},


			//核心
			{ translation_hash("Language"), L"切换语言" },
			{ translation_hash("Plugins"), L"脚本插件" },
			{ translation_hash("Menu"), L"菜单位置" },
			{ translation_hash("Multiple modules"), L"多开插件" },
			{ translation_hash("Utility"), L"活化剂插件" },
			{ translation_hash("Evade"), L"躲避" },
			{ translation_hash("OpenUtilities"), L"Open活化剂" },
			{ translation_hash("Misc plugins"), L"其他插件" },
			{ translation_hash("AuroraPrediction"), L"Aurora预判" },
			{ translation_hash("LordsPred"), L"Lords预判" },
			{ translation_hash("ZEDithPred"), L"Zedith预判" },
			{ translation_hash("SebasPredicition"), L"Sebas预判" },
			{ translation_hash("AJK - KoreanPings"), L"AJKping" },

			//Kiri 佐伊
			{ translation_hash("Predictions"), L"预判" },
			{ translation_hash("Semi-E"), L"手动热键E" },
			{ translation_hash("R/W Under-Turret"), L"在敌方防御塔下是否允许使用R/W" },
			{ translation_hash("Wait for E"), L"先放E再Q" },
			{ translation_hash(" ^-Type:"), L"种类" },
			{ translation_hash("E is on cooldown"), L"E在冷却中" },
			{ translation_hash("Enemy hit by E"), L"E打到敌人了" },
			{ translation_hash("use E through Walls"), L"可以隔墙E" },
			{ translation_hash("Don't R into enemy if <=X HP%"), L"如果敌人血量低于，则不使用R" },
			{ translation_hash("Don't R into X enemies"), L"对面有X个敌人时候不使用R" },
			{ translation_hash("Min. Mana %"), L"在x%魔法的时候停止" },
			{ translation_hash("Try Short Q"), L"尝试用短距离Q攻击" },
			{ translation_hash("Use E through Walls"), L"可隔墙用E" },
			{ translation_hash("Auto Short Q on Killable"), L"可击杀就Q" },
			{ translation_hash("Auto Short E on killable"), L"可击杀就E" },
			{ translation_hash("Auto E on CC/Channel"), L"自动对被控的敌人用E" },
			{ translation_hash("Auto E on Special Spells"), L"自动对使用特殊技能的敌人用E" },
			{ translation_hash("E Anti-Gapclose Settings"), L"反突进E设置" },
			{ translation_hash("Auto R+AA on Killable"), L"可击杀就自动R+平A" },
			{ translation_hash("Auto R+Short Q on Killable"), L"可击杀就自动R+Q" },
			{ translation_hash("Don't AA Asleep enemy"), L"不要平A打睡着的敌人" },
			{ translation_hash("Heal settings"), L"治疗设置" },
			{ translation_hash("Ghost settings"), L"疾跑设置" },
			{ translation_hash("Barrier settings"), L"护盾设置" },
			{ translation_hash("Exhaust settings"), L"虚弱设置" },
			{ translation_hash("Smite settings"), L"惩戒设置" },
			{ translation_hash("Cleanse settings"), L"净化设置" },
			{ translation_hash("Ignite settings"), L"点燃设置" },
			{ translation_hash("Enable Combo usage"), L"空格的时候使用" },
			{ translation_hash("Enable automatic usage"), L"可自动使用" },
			{ translation_hash("If my Health <= X%"), L"在我生命低于X%的时候使用" },
			{ translation_hash("Cleansable spells"), L"使用净化类技能" },
			{ translation_hash("Enable Combo usage to extend Q2"), L"使用连招的时候用超长Q2" },

			//Kiri 刀妹
			{ translation_hash("Q Usage"), L"Q模式" },
			{ translation_hash("To Mouse"), L"鼠标光标方向Q" },
			{ translation_hash("Use Q to gapclose on minions:"), L"用Q杀兵时" },
			{ translation_hash("Towards Enemy"), L"朝着敌人" },
			{ translation_hash("Towards Mouse"), L"朝着鼠标光标" },
			{ translation_hash("Use Q to dash around enemy"), L"用Q在敌人周围突进" },
			{ translation_hash("Dash around type"), L"在周围突进的目的是" },
			{ translation_hash("To Stack Passive"), L"攒被动" },
			{ translation_hash("If <= X Health"), L"生命低于X" },
			{ translation_hash("Dash around if <= X% Health"), L"生命低于X%以下Q敌人周围" },
			{ translation_hash("Try to AA>Q wave"), L"尽量用平A+Q的方式清兵" },
			{ translation_hash(" ^- W delay (ms)"), L"使用W的延迟" },
			{ translation_hash("Use W on Minion Logic"), L"W对小兵使用" },
			{ translation_hash("Use E1"), L"使用E1" },
			{ translation_hash("E1 Position"), L"E1位置" },
			{ translation_hash("Predicted Position"), L"预判敌人会走到的位置" },
			{ translation_hash("Player Position"), L"敌人现在的位置" },
			{ translation_hash("For Behind"), L"超远距离" },
			{ translation_hash("Hold E1 if can Multi-E within X range"), L"如果能E到好几个人就慢点放E" },
			{ translation_hash("R usage:"), L"在如下条件使用R" },
			{ translation_hash("At X health"), L"在X生命的时候使用" },
			{ translation_hash("Only if Killable"), L"必杀人的时候使用" },
			{ translation_hash("Multi-hit"), L"能打好几个人的时候使用R" },
			{ translation_hash("Don't R if Enemy kilable with X AA"), L"如果X下平A能杀就不用R" },
			{ translation_hash("Force R if hits X enemies"), L"如果能打到X个敌人就强制R" },
			{ translation_hash("Force R>Flash if hits X enemies"), L"如果能打到X个敌人就强制R闪" },
			{ translation_hash("Inlude X AA for damage calc."), L"伤害计算包含X下平A" },
			{ translation_hash("W delay (ms)"), L"W延迟" },
			{ translation_hash("Don't block under-turret"), L"不在敌方塔下用W" },
			{ translation_hash("Ignore Circular spells"), L"无视圆圈技能" },
			{ translation_hash("Ignore FOW spells"), L"无视无视野技能" },
			{ translation_hash("Speed buffer"), L"延迟使用W时间" },
			{ translation_hash("Skillshot settings"), L"w挡弹道技能设置" },
			{ translation_hash("Targetd spells settings"), L"W挡指向性技能设置" },
			{ translation_hash("Usage cases"), L"使用情况" },
			{ translation_hash("WILL use W if ANY of these cases matches!"), L"在以下各种条件满足时使用W" },
			{ translation_hash("If spell is CC"), L"打过来的是控制技能" },
			{ translation_hash("If spell will kill"), L"打过来的技能会杀死我" },
			{ translation_hash("If spell deals >= X% damage"), L"打过来的技能会造成X%伤害以上" },
			{ translation_hash("Auto Q on Killable"), L"自动Q抢人头" },
			{ translation_hash(" ^-Include X AA"), L"自动Q+X下平A抢人头" },
			{ translation_hash(" ^- Only if <= X enemies nearby"), L"只会在X个敌人在旁边时这样做" },
			{ translation_hash("Auto Release W if not of range"), L"敌人没跑出W距离以外就自动释放W2" },
			{ translation_hash("Auto Release W on Killable"), L"能杀就自动放W2" },
			{ translation_hash("Auto Charge W on Killable"), L"能杀就自动攒W" },
			{ translation_hash("Auto W on Spellshield"), L"对面放护盾就W" },
			{ translation_hash("Auto E on CC/Channel"), L"对面被控住了就自动E" },
			{ translation_hash("E Anti-Gapclose Settings"), L"E反突进设置" },
			{ translation_hash("Priority"), L"优先级" },
			{ translation_hash("Killable Minion then Hero"), L"先Q可以Q死的小兵->Q英雄" },
			{ translation_hash("Hero then killable Minion"), L"先Q英雄->可Q死的兵" },
			{ translation_hash("Only Closest Hero to Mouse"), L"只会Q离鼠标最近的英雄" },
			{ translation_hash("Only Closest Killable Minion to Mouse"), L"只会Q离鼠标最近的可Q死的兵" },
			{ translation_hash("Radius"), L"鼠标范围" },
			{ translation_hash("Ignore Q range checks"), L"无视Q范围判定" },

			//kiri女警
			{ translation_hash("Q Mode:"), L"Q模式" },
			{ translation_hash("Don't Q if enemies in AA range"), L"普攻击范围内不要Q" },
			{ translation_hash("W Mode:"), L"W模式" },
			{ translation_hash("Logic"), L"逻辑" },
			{ translation_hash("With E"), L"和E一起放" },
			{ translation_hash("Don't E into X enemies"), L"不要E到X敌人内" },
			{ translation_hash("Enable Logic for chasing"), L"用E反向突进追人" },
			{ translation_hash("Use proforce Combo if Killable"), L"狂风之力抢头" },
			{ translation_hash("Auto W on CC/Channel"), L"对面被控住了就自动W" },
			{ translation_hash("Auto W on Special Spells"), L"对面放特殊技能了就自动W" },
			{ translation_hash("Auto W behind Turret"), L"在敌方塔下自动放W" },
			{ translation_hash("W Anti-Gapclose Settings"), L"W反突击设置" },
			{ translation_hash("Block W if can kill with X AA"), L"X下平A能杀就不用W" },
			{ translation_hash("Block W if X enemies in range"), L"X范围内不适用W" },
			{ translation_hash(" ^- Range"), L"范围" },
			{ translation_hash("Auto E on Killable"), L"自动E抢人头" },
			{ translation_hash("Auto E on Special Spells"), L"自动E在用特殊技能的敌人" },
			{ translation_hash("Anti-melee E"), L"自动E反突进" },
			{ translation_hash("Auto W on Killable"), L"自动W抢人头" },
			{ translation_hash("Auto W on Special Spells"), L"自动W在用特殊技能的敌人" },
			{ translation_hash("Anti-melee W"), L"自动W反突进" },
			{ translation_hash("Auto Q on Killable"), L"自动Q抢人头" },
			{ translation_hash("Auto Q on Special Spells"), L"自动Q在用特殊技能的敌人" },
			{ translation_hash("Anti-melee Q"), L"自动Q反突进" },
			{ translation_hash("Block E if can kill with X AA"), L"X下平A能杀就不用E" },
			{ translation_hash("Don't Auto E in X enemies"), L"X个敌人不使用E" },
			{ translation_hash("Block E if would dash uhnder-turret"), L"不要E进敌方塔下" },
			{ translation_hash("Save E against Blink/Dash"), L"敌人瞬移时不使用E" },
			{ translation_hash(" ^-Blink/Dash blacklist"), L"瞬移突进黑名单" },
			{ translation_hash("E Anti-Gapclose Settings"), L"E反突进" },
			{ translation_hash("Auto R on Killable"), L"自动R抢头" },
			{ translation_hash(" ^-Don't under-turret"), L"在敌方塔下不用R" },
			{ translation_hash("Don't R if enemies in X range"), L"X范围内有敌人则不用R" },
			{ translation_hash("Don't R if allies in X range near enemy"), L"敌人X范围内有队友则不R" },
			{ translation_hash("R Blacklist"), L"R黑名单" },
			{ translation_hash("Use Blue trinket if enemy is recalling in FoW and Killable"), L"如果正回家的敌人可以被R干掉但是无视野则用蓝眼" },

			//kiri zeri
			{ translation_hash("Ignore colision"), L"无视碰撞" },
			{ translation_hash("  ^-Usage"), L"使用条件" },
			{ translation_hash("Normal + Walls"), L"正常+墙" },
			{ translation_hash("Only Walls"), L"只有墙" },
			{ translation_hash("If Collision"), L"如果碰撞" },
			{ translation_hash("Killable or Collision"), L"可击杀或者碰撞" },
			{ translation_hash("E Logic:"), L"E逻辑" },
			{ translation_hash("E End Pos safety range"), L"安全检测距离" },
			{ translation_hash("Don't E in X enemies"), L"X个敌人不要E" },
			{ translation_hash("Use E to gapclose"), L"用E突进" },
			{ translation_hash("R Usage"), L"R使用" },
			{ translation_hash("Don't waste R if Enemy <= X% Health"), L"如果敌人生命低于X%，不要用R" },
			{ translation_hash("Include X Q for damage calc."), L"伤害计算包含X下平A" },
			{ translation_hash("AA Usage:"), L"平A使用" },
			{ translation_hash("Only if Passive >= X"), L"只有被动>=X的时候" },
			{ translation_hash("  ^- AA only if Passive >= X%"), L"只有被动>= X的时候才平A" },
			{ translation_hash("Jungle Clear"), L"清野" },
			{ translation_hash("Strucature Clear"), L"打塔" },
			{ translation_hash("Auto W on CC"), L"自动W打被控住的敌人" },
			{ translation_hash("AA only if Passive >= X%"), L"被动>X的时候才会平A" },

			//kiri火男
			{ translation_hash("Semi-R"), L"手动热键R" },
			{ translation_hash("Q->Flash->E"), L"Q->闪现->E" },
			{ translation_hash("Save EQ for Dashes"), L"对方突进的时候不放EQ" },
			{ translation_hash("Save E>Q Blacklist"), L"EQ黑名单" },
			{ translation_hash("Combo Mode:"), L"连招" },
			{ translation_hash("  ^-Only if Stuns"), L"只用来眩晕敌人" },
			{ translation_hash("Try to time W>Q"), L"快速WQ" },
			{ translation_hash("Use Spread Logic"), L"使用E扩散技巧" },
			{ translation_hash("E->Q Anti-Gapclose Settings"), L"E->Q反突进设置" },
			{ translation_hash("E>Q Interrupt Settings"), L"E->Q打断敌人技能设置" },
			{ translation_hash("Range Check Strictness"), L"范围检测" },
			{ translation_hash("Hitchance"), L"命中率" },
			{ translation_hash("Include custom check cases"), L"包含自定义判定" },

			//kiri orianna
			{ translation_hash("E Shielding"), L"E给盾" },
			{ translation_hash("R Flash"), L"R闪" },
			{ translation_hash("Use E>Q Logic"), L"用EQ打人" },
			{ translation_hash("Multi Hit"), L"打多人" },
			{ translation_hash(" ^ Include only ready spells"), L"包括其他CD好了的技能" },
			{ translation_hash("Auto Q"), L"自动Q" },
			{ translation_hash("Include W in Auto Q Harass"), L"QW骚扰" },
			{ translation_hash("Priority Ally"), L"队友优先级" },
			{ translation_hash("Ally Blacklist"), L"队友黑名单" },
			{ translation_hash("Auto Attack Settings"), L"自动攻击设置" },
			{ translation_hash("Auto E on Enaging Ally"), L"把E自动给到要开团的队友" },
			{ translation_hash("Engage Spells"), L"配合队友的开团技能" },
			{ translation_hash("R Interrupt Settings"), L"R打断敌人技能设置" },

			//Kiri Varus
			{ translation_hash("Semi-R Priority"), L"手动热键R优先级" },
			{ translation_hash("Closest to Mouse"), L"靠近鼠标的位置" },
			{ translation_hash("Closest to Player"), L"靠近玩家的位置" },
			{ translation_hash("Min. W Stacks"), L"使用W的最低层数" },
			{ translation_hash("Wait for Full Charge"), L"等蓄满了再用" },
			{ translation_hash("Wait for Full Charge if can Kill"), L"蓄满能杀就等蓄满了再用" },
			{ translation_hash("W Usage:"), L"使用W" },
			{ translation_hash("Auto Q Release on Manual Q"), L"手动按Q时自动帮你放" },
			{ translation_hash("  ^- Wait for Full Charge"), L"等到Q蓄满" },
			{ translation_hash("Block E if Attack Speed >= X"), L"如果攻速大于X就不用E" },
			{ translation_hash("E Anti-Gapclose Settings"), L"E反突进" },

			//Kiri 老鼠
			{ translation_hash("E Usage:"), L"使用E" },
			{ translation_hash("Min. stacks for E"), L"可以E的最小层数" },
			{ translation_hash("R Multi-Hit"), L"R尝试穿透多人" },
			{ translation_hash("Auto Q on Reset"), L"自动使用Q如果CD重置" },
			{ translation_hash(" ^ Only if there's enemies in range"), L"只在敌人在范围内的时候这样做" },
			{ translation_hash("Block W if R is active"), L"R期间不用W" },
			{ translation_hash("Block W if in Stealth"), L"隐身期间不用W" },
			{ translation_hash("Auto E on X Killable Champions"), L"自动用E如果能杀X个英雄" },
			{ translation_hash("  ^- predict incoming damage from:"), L"把敌人会吃到的其他伤害计算进来" },
			{ translation_hash("  ^- include Ignite damage"), L"把点燃伤害计算进来" },
			{ translation_hash("Try AA>E>AA logic"), L"使用平A->E->平A的逻辑" },
			{ translation_hash("Force E if First Stricke is about to end"), L"打完一轮强制E" },
			{ translation_hash("Auto E on Killable Monsters"), L"如果可以杀野怪就自动E" },
			{ translation_hash("  ^- Monster Types:"), L"野怪种类" },
			{ translation_hash("  ^- Only if Farm toggle is active"), L"只有在刷兵启动的时候" },

			//kiri萨米拉
			{ translation_hash("W Dodge"), L"W格挡" },
			{ translation_hash("E Under-Turret"), L"在敌方塔下E" },
			{ translation_hash("Instant S Rank"), L"立刻S" },
			{ translation_hash("Semi-E"), L"手动热键E" },
			{ translation_hash("Try to use W before E"), L"先W再E" },
			{ translation_hash("E Gapclose usage:"), L"E突进" },
			{ translation_hash("E Target usage:"), L"E对目标使用" },
			{ translation_hash("Min Grade:"), L"最低层数" },
			{ translation_hash("Don't E if <=% Health"), L"X%血一下不要E" },


			//Kiri vayne
			{ translation_hash("Q Under-Turret"), L"敌方塔下不Q" },
			{ translation_hash("E Flash"), L"E闪" },
			{ translation_hash("Semi-E Priority"), L"手动热键优先级" },
			{ translation_hash("Q to Wall for AA Rest"), L"往墙那边Q重置普攻" },
			{ translation_hash("Q to position for E"), L"Q到可以把敌人E到墙的位置" },
			{ translation_hash("Don't Q in X enemies"), L"不要朝X个敌人Q" },
			{ translation_hash("Q only if W2 stacks"), L"只在挂2层W的时候Q" },
			{ translation_hash("Use Q to gapclose"), L"Q突进" },
			{ translation_hash("Simple"), L"简单" },
			{ translation_hash("Advanced"), L"高级" },
			{ translation_hash("Push Distance"), L"X距离之内使用E" },
			{ translation_hash("Focus Orbwalker Target"), L"对正在走A的目标使用" },
			{ translation_hash("Min. enemies for R"), L"用R的最低敌人数量" },
			{ translation_hash("Auto Q on R case"), L"开R了自动Q" },
			{ translation_hash("Cancel animation"), L"取消动画前摇后摇" },
			{ translation_hash("Q Anti-Gapclose Settings"), L"Q反突进" },
			{ translation_hash("Auto ward bush on E"), L"E到草里后自动插眼" },
			{ translation_hash("Anti-melee E"), L"反近战E" },
			{ translation_hash("Don't E if can kill with X AA"), L"X下平A能打死就不要E" },
			{ translation_hash("E Interrupt Settings"), L"E打断敌人技能" },
			{ translation_hash("Don't AA while invisiable for X ms"), L"隐身之后Xms之内不要平A" },
			{ translation_hash("if <= X HP"), L"如果在X%血以下" },
			{ translation_hash("OR if enemy on me"), L"或者敌人不在我身边" },
			{ translation_hash("Priority Target with W Stacks"), L"先打挂W的敌人" },

			//kiri 蛇女
			{ translation_hash("Save W for Dashes"), L"敌人要突进再用W" },
			{ translation_hash("Save W Blacklist"), L"W黑名单" },
			{ translation_hash("  ^-Only if Facing"), L"只在面朝你的时候使用" },
			{ translation_hash("  ^- Try backwards R"), L"尝试向后R" },
			{ translation_hash("Disable AA in Combo/Harass"), L"空格/骚扰的时候关闭普攻" },
			{ translation_hash("  ^- Level >= X"), L"等级>=X的时候" },
			{ translation_hash("Pause AA logic in Fast Lane Clear"), L"快速清线的时候不平A" },
			{ translation_hash("Pause AA logic in Lane Clear"), L"清线的时候不平A" },
			{ translation_hash("Pause AA logic in Last Hit"), L"补最后一刀时候不平A" },
			{ translation_hash("If not poisoned"), L"如果没有中毒" },
			{ translation_hash("Priority enemies with poison"), L"先打中毒的敌人" },
			{ translation_hash("Only if Facing"), L"只在面对的时候" },
			{ translation_hash("Force R if hits X facing enemies"), L"能打到面对你的X个敌人就R" },
			{ translation_hash("Force R if hits X any enemies"), L"能打到X个敌人的时候就R" },
			{ translation_hash("Include X R for damage calc."), L"把R的伤害也计算在内" },

			//Kiri诺手
			{ translation_hash("W mode"), L"W模式" },
			{ translation_hash("Force W if at the max AA range"), L"在最大平A距离边缘W" },
			{ translation_hash("E Mode:"), L"E模式" },
			{ translation_hash("Outside AA range"), L"平A距离以外" },
			{ translation_hash("Q outside lock"), L"Q磁力吸附" },
			{ translation_hash(" ^Don't lock if under-turret"), L"在敌人塔下不要吸附" },
			{ translation_hash("Include passive damage"), L"包含被动伤害" },
			{ translation_hash("  ^- Max. passive stacks to calculate"), L"计算最大被动层数" },
			{ translation_hash("Priority R over other spell"), L"R优先于其他技能" },
			{ translation_hash("Priority target with X passive stacks"), L"有X层被动的优先于其他目标" },

			//kiri 轮子妈
			{ translation_hash("E Dodge"), L"E格挡" },
			{ translation_hash("Pause Evade if E is active"), L"E开了就不用躲避" },


			//kiri jinx
			{ translation_hash("Try to Q AOE"), L"用火箭模式AOE" },
			{ translation_hash("Switch to Minigun if no enemies"), L"如果周围没有敌人就切换到机关枪" },
			{ translation_hash("Don't W if enemies in AA range"), L"敌人不在平A范围内就不W" },
			{ translation_hash("Slow/CC/Undodge"), L"被缓慢/被控/无法躲避" },
			{ translation_hash("Auto Minigun in Farm"), L"清兵的时候自动切到机关枪" },
			{ translation_hash("Block Auto W if enemies in AA RANGE"), L"敌人在平A范围内就不自动W" },
			{ translation_hash("Don't Auto R if Blink/Dash ready"), L"敌人有闪/位移不要自动R" },
			{ translation_hash("  ^- Blink/Dash blacklist"), L"闪现/位移黑名单" },
			{ translation_hash("Ignore under-turret"), L"在敌方塔下就无视" },
			{ translation_hash("Only if gapcloses to me"), L"只在敌方突进我的角色的时候使用" },
			{ translation_hash("Cast Position:"), L"使用位置" },
			{ translation_hash("Towards the end"), L"用最远的" },


			{ translation_hash("Hold"), L"按住才有用" },
			{ translation_hash("Toggle"), L"按一下就开关" },
			{ translation_hash("Dodging near enemies settings"), L"躲避离你很近的英雄设定" },
			{ translation_hash("Prioritize enemy plants/boxes/turrets over minions in laneClear"), L"在清线模式中，盒子/花/船长的桶/炮台优先级高于小兵" },
			{ translation_hash("Orbwalking speed %"), L"走A速度" },
			{ translation_hash("Use Anti-Stutter"), L"角色不会因为走A抽搐" },
			{ translation_hash("Glow"), L"玩家角色高亮" },
			{ translation_hash("Blur"), L"模糊程度" },
			{ translation_hash("Thickness"), L"线宽" },
			{ translation_hash("Color"), L"颜色" },
			{ translation_hash("  ^-if Hits X Minions"), L"只会打到X个小兵的时候使用" },
			{ translation_hash("Utility plugins"), L"活化剂插件" },
			{ translation_hash(" Utility"), L"实用工具" },
			{ translation_hash("Selected target glow"), L"选中目标高亮" },
			{ translation_hash("Range Check Strictness:"), L"范围判定等级" },
			{ translation_hash("KiriAIO - Permashow"), L"Kiri的附带的热键菜单" },
			{ translation_hash("Line Thickness"), L"线圈粗细" },
			{ translation_hash("Only if X traps ready"), L"只会当X个夹子CD好的时候使用" },
			{ translation_hash("Use Galeforce Combo if Killable"), L"如果能杀就用狂风之力" },
			{ translation_hash("Auto Q on CC/Channel"), L"自动对被控的敌人Q" },
			{ translation_hash("Block Auto Q if enemies in AA range"), L"敌人在普攻范围内则不自动Q" },
			{ translation_hash("Block Q if can kill with X AA"), L"能几下打死的情况下不用Q" },
			{ translation_hash("  ^- Range"), L"范围" },
			{ translation_hash("  ^- Don't under-turret"), L"不要在敌方塔下使用" },
			{ translation_hash("Semi-Q"), L"手动热键Q" },
			{ translation_hash("Camera height (zoomhack)"), L"无限视距" },
			{ translation_hash("ESP options"), L"连线设置" },
			{ translation_hash("Champion range (ground)"), L"敌人的线圈" },
			{ translation_hash("Exp tracker"), L"显示经验值条" },
			{ translation_hash("Draw mode"), L"绘制模式" },
			{ translation_hash("Distance"), L"距离" },
			{ translation_hash("Portrait scale"), L"比例尺" },
			{ translation_hash("Waypoints mode"), L"路径点模式" },
			{ translation_hash("Champion name"), L"英雄名称" },
			{ translation_hash("Only FoW"), L"只在无视野的时候启用" },
			{ translation_hash("Auto Oracle's Lens"), L"自动开扫描" },
			{ translation_hash("Score (in % between min, max)"), L"插眼得分最高的位置" },
			{ translation_hash("Track even if visable"), L"能看到也追踪位置" },
			{ translation_hash("Only ping if visable"), L"只会在所有人都能看到的情况下ping" },

			//Yuu 
			//kindred
			{ translation_hash("Mouse Pos"), L"鼠标光标" },
			{ translation_hash(" ^- to Gapclose"), L"突进" },
			{ translation_hash(" ^- target is under turret"), L"目标在敌方防御塔下" },
			{ translation_hash(" ^- Usage:"), L"使用" },
			{ translation_hash(" ^- Use on:"), L"用在X的身上" },
			{ translation_hash(" ^- Only When Enemies are Nearby"), L"只当敌人在附近时" },
			{ translation_hash(" ^- Nearby Enemies Range"), L"附近敌人范围" },
			{ translation_hash("Not Use Q in R buff"), L"开R的时候不用Q" },
			{ translation_hash(" ^- Use Q if target has <% HP"), L"目标在百分之X HP以下时用Q" },
			{ translation_hash("Killsteal"), L"抢头" },
			{ translation_hash("Animation cancel"), L"取消前摇后摇动画" },
			{ translation_hash("Q Animation"), L"Q前摇后摇动画" },
			{ translation_hash("Use Q to evade skillshots"), L"用Q来躲避弹道技能" },
			{ translation_hash("Evade distance"), L"躲避距离" },
			{ translation_hash("Farming"), L"刷野刷兵" },
			{ translation_hash("Farm"), L"刷野刷野" },
			{ translation_hash("Use Q to Wall Jump"), L"用Q过墙" },
			{ translation_hash("Only Draw If Spell Ready"), L"只在技能CD好了的时候显示范围" },
			{ translation_hash("Damage Drawings"), L"显示伤害" },
			{ translation_hash("Mark Drawings"), L"显示千珏标记" },

			//Ashe
			{ translation_hash("W cone collision"), L"W阻挡" },
			{ translation_hash("Use W in Q buff"), L"开Q的时候用W" },
			{ translation_hash("Use E when last vision"), L"视野要没了就E" },
			{ translation_hash("Use Smart R"), L"逻辑R" },
			{ translation_hash("R max range"), L"R最大使用范围" },
			{ translation_hash("Not cast R min range"), L"R最小使用范围" },
			{ translation_hash("Semi R Mode"), L"手动热键R模式" },
			{ translation_hash("Only Select target"), L"只选择目标" },
			{ translation_hash("Seleting Logic"), L"选择逻辑" },
			{ translation_hash("Use Q before expire"), L"在技能时限结束之前用Q" },
			{ translation_hash(" ^- Only in Combo Mode"), L"只在空格的时候用" },
			{ translation_hash(" ^- Only in Clear Mode"), L"只在清兵的时候用" },
			{ translation_hash("In Channeling Spells"), L"用于异常状态技能" },
			{ translation_hash(" ^- Spells to Cancel:"), L"要打断的技能" },
			{ translation_hash("On Gapclose"), L"用于突进" },
			{ translation_hash("On Dashing Spells"), L"用于突进技能" },
			{ translation_hash("Anti melee Range 0=disabled"), L"反突进范围判定" },
			{ translation_hash("Min minions"), L"可厨房的最少数量兵" },
			{ translation_hash("Line Tickness"), L"线条粗细" },
			{ translation_hash("Draw W Damage"), L"显示W伤害" },
			{ translation_hash("Draw x AA Damage"), L"显示X下平A的伤害" },
			{ translation_hash("Combo Damage Color"), L"显示连招伤害" },
			{ translation_hash("Draw Range W"), L"显示W范围" },

			//Akali
			{ translation_hash("Use W if Health <"), L"如果生命低于X则用W" },
			{ translation_hash("Use W for energy"), L"为了能量用W" },
			{ translation_hash("Execute if health < %"), L"如果生命低于X就斩杀" },
			{ translation_hash("Enemy health % for all in"), L"如果敌人生命为X%就全套技能打出" },
			{ translation_hash("^~minimum minions to hit"), L"最少可以打几个兵" },
			{ translation_hash("Use Q pred"), L"预判Q" },

			//illaoi
			{ translation_hash(" ^- In Spirit"), L"在灵魂中" },
			{ translation_hash("W to Gapclose"), L"用W突进" },
			{ translation_hash(" ^ -Use under enemy turret"), L"在敌人塔下使用" },
			{ translation_hash(" ^- Only when soul is nearby"), L"只在灵魂在附近时使用" },
			{ translation_hash("Enemy Number >="), L"敌人数量大于" },
			{ translation_hash("W AA Reset"), L"W重置普攻" },
			{ translation_hash("On Turret On Enemy"), L"对塔对敌人" },
			{ translation_hash("On Wards"), L"对眼" },
			{ translation_hash("Auto E on"), L"自动对X用E" },
			{ translation_hash("Immobile"), L"不动的" },
			{ translation_hash("Dashing"), L"突进/瞬移" },
			{ translation_hash("Hitchance E"), L"E命中率" },

			//lulu
			{ translation_hash("Draw Damage"), L"显示伤害" },
			{ translation_hash("Daddy Settings"), L"大爹模式" },
			{ translation_hash("Only Carry Daddy?"), L"大爹模式" },
			{ translation_hash("Select your carry"), L"选择带飞的爹" },
			{ translation_hash("Superman"), L"超人模式" },
			{ translation_hash("Only buff ally if W and E is ready"), L"只在W和E冷却好的时候给队友buff" },
			{ translation_hash("Only if ally health <= (X)"), L"只在队友生命低于X的时候使用" },
			{ translation_hash("Use E in entity to hit Q"), L"用EQ打人" },
			{ translation_hash("Use Q from PIX only if pix is far from my hero"), L"如果被动精灵离我太远，我就用它放Q" },
			{ translation_hash("Enable KS"), L"允许抢人头" },
			{ translation_hash("for now harass Q & E use combo configs"), L"Q和E的骚扰用连招里的逻辑" },
			{ translation_hash("Use Q from pix pos"), L"通过被动精灵放Q" },
			{ translation_hash("Use only if mana > (x) | 0=Disabled"), L"只在魔法大于X%的时候使用，选0就是不用" },
			{ translation_hash("Auto Spells in"), L"自动放技能" },
			{ translation_hash("Spells in Buff's"), L"加buff的技能" },
			{ translation_hash("Auto W in Buff's"), L"自动给W buff" },
			{ translation_hash("Auto E in Buff's"), L"自动给E buff" },
			{ translation_hash("Spells to Buff:"), L"自动给buff的技能" },
			{ translation_hash("[Runes/Items]"), L"符文和装备" },
			{ translation_hash("Use E Speed when E is on CD"), L"无冷却使用E" },
			{ translation_hash("Ally Prority"), L"队友优先级" },
			{ translation_hash("Enemy Prority"), L"敌人优先级" },
			{ translation_hash("Use E to shield big damage"), L"如果伤害太高就用E阻挡" },
			{ translation_hash("^ Only if damage >= X% ally health"), L"只当要承受的伤害比队友百分之X的血量高时" },
			{ translation_hash("Use E in Ally in enemy AA"), L"敌方平A你队友时给队友用E" },
			{ translation_hash("Skills Blacklist"), L"技能黑名单" },
			{ translation_hash("Auto Laugh"), L"自动嘲笑" },
			{ translation_hash("Use fixed prority for all ally skills"), L"对所有队友的技能排列优先级" },
			{ translation_hash("Fixed prority list"), L"优先级列表" },
			{ translation_hash("Pix Settings"), L"被动精灵设置" },
			{ translation_hash("Draw Pix Position"), L"显示被动精灵位置" },
			{ translation_hash("Draw Tickness"), L"显示线圈" },
			{ translation_hash("Spells Configs"), L"技能设置" },
			{ translation_hash("Max Q range"), L"最大Q范围" },
			{ translation_hash("Enemy distance to ally"), L"敌人到队友的距离" },
			{ translation_hash("min mana% to use Q"), L"最少多少魔法可以放Q" },
			{ translation_hash("Ally health % <="), L"队友生命值低于X" },
			{ translation_hash("W ally with slow buff"), L"队友被缓慢了就给W" },
			{ translation_hash("Ally health >= %"), L"队友生命大于等于X%" },
			{ translation_hash("Myhero health >= %"), L"我的英雄生命大于等于" },
			{ translation_hash("Only if R can knockup >= (X) enemys"), L"只会在R可以把X个敌人弹飞时" },
			{ translation_hash("Anti Gapcloser"), L"反突进" },
			{ translation_hash("Spells to Cancel:"), L"要取消的技能" },
			{ translation_hash("Savers"), L"救命" },
			{ translation_hash("Use W Speed when E is on CD"), L"E在冷却的时候使用W" },
			{ translation_hash("Health <= X"), L"生命小于等于" },
			{ translation_hash("Spells to Cancel:"), L"要打断的技能" },
			{ translation_hash("Buff lulu if no ally in range"), L"Buff自己如果附近没队友" },
			{ translation_hash("Spells Config"), L"技能设置" },

			//zac
			{ translation_hash("Use Smart Q"), L"使用智能Q" },
			{ translation_hash("Allow Tower Diving with E"), L"E允许塔杀" },
			{ translation_hash("Use E in Combo"), L"连招使用E" },
			{ translation_hash("R if Enemy Number >="), L"使用R当敌人>=x" },
			//{ translation_hash(""), L"" },
			//{ translation_hash(""), L"" },
			//{ translation_hash(""), L"" },
			//{ translation_hash(""), L"" },
			//{ translation_hash(""), L"" },
			//{ translation_hash(""), L"" },





			//maokai
			{ translation_hash("Use W in Combo"), L"连招中使用W" },
			{ translation_hash("R Min Targets"), L"放R的最少敌人数量" },
			{ translation_hash("Use E on Immobile"), L"对不同的敌人用E" },
			{ translation_hash("Use E on Dashing"), L"对瞬移/突进的敌人用E" },

			//morg
			{ translation_hash("Q min range"), L"最小Q范围" },
			{ translation_hash("Q max range"), L"最大Q范围" },
			{ translation_hash("Priority Q"), L"Q优先级" },
			{ translation_hash(" ^-Only on CC"), L"只对被控的使用" },
			{ translation_hash("E Ally with Slow Buff"), L"对被减慢队友使用" },
			{ translation_hash("E Ally with Poison|Liandry's"), L"对被毒/持续伤害/的队友使用" },
			{ translation_hash("E in Incoming Dangerous Spell"), L"对马上要被危险技能攻击的队友使用" },
			{ translation_hash(" ^-Spells to Cancel"), L"不对这些技能使用" },
			{ translation_hash("URF | Auto Harass"), L"无限火力，自动骚扰" },
			{ translation_hash("Auto Q"), L"自动Q" },
			{ translation_hash("Auto W on cc"), L"自动对被控住的敌人W" },
			{ translation_hash("Auto E myself"), L"自动E自己" },
			{ translation_hash("Hitchance"), L"命中率" },

			//nidalee
			{ translation_hash("Auto use R meless"), L"自动R边近战" },
			{ translation_hash("Human Combo"), L"人模式" },
			{ translation_hash("Panther Combo"), L"豹模式" },
			{ translation_hash("Use E after Q (for AS boost and heal)"), L"E之后Q" },
			{ translation_hash("Use AA-Q in combo (off = just Q)"), L"平A之后Q，关闭就是只Q" },
			{ translation_hash("W in turret"), L"塔下W" },
			{ translation_hash(" ^- Not use in TryndaR/JaxE/ShenW"), L"不用于蛮子R/贾克斯E/慎的W" },
			{ translation_hash("Auto W (human) On CC"), L"人形态对被控的敌人自动W" },
			{ translation_hash("Auto W (human) On Gapclose"), L"人形态对突进的敌人自动W" },
			{ translation_hash("Auto E (human) Allies"), L"自动E队友" },
			{ translation_hash("^~only when ally HP <= X%"), L"只在队友的生命值低于百分之X" },
			{ translation_hash("Auto E (human) Self"), L"人形态自动E自己" },
			{ translation_hash("^~ only when my HP <= X%"), L"只在自己的生命低于百分之X" },
			{ translation_hash("Use Q Human"), L"人形态Q" },
			{ translation_hash("Use E Panther"), L"豹形态E" },
			{ translation_hash("Auto Switch To Panther On Gapclose"), L"对面突进时自动变豹" },
			{ translation_hash("Auto Switch To Panther"), L"自动变豹子" },
			{ translation_hash("^~ don't switch under enemy turret"), L"不要在敌方塔下切换形态" },
			{ translation_hash("Human Combo"), L"人类模式" },
			{ translation_hash("Panther Combo"), L"豹子模式" },
			{ translation_hash("Use W (auto switch to panther)"), L"自动切换成豹子之后W" },

			//Noc
			{ translation_hash("Priority R"), L"R优先级" },
			{ translation_hash("if Target HP under mode"), L"之后目标生命值低于X" },
			{ translation_hash("Combo Only Selected Target"), L"只对选择的目标连招" },
			{ translation_hash("Auto Trinket in R"), L"R时自动用铁刺鞭" },
			{ translation_hash("Use W in skillshots"), L"对弹道技能用W" },

			//nunu
			{ translation_hash(" ^- Maximum Range"), L"最大范围" },
			{ translation_hash("Spam E (urf)"), L"无限火力狂E" },
			{ translation_hash(" ^- Colision in Minions"), L"兵碰撞阻挡" },
			{ translation_hash("Disable Orbwalker in R"), L"R时关闭走砍" },
			{ translation_hash("Disable Evade in R"), L"R时关闭躲避" },
			{ translation_hash("Use Q in Epic Monsters"), L"对大型野怪用Q" },
			{ translation_hash("Use Q in Red Blue"), L"对红蓝buff用Q" },
			{ translation_hash("JungleSteal"), L"抢野怪" },
			{ translation_hash("Smite+Q Burst"), L"惩戒+Q抢野怪" },
			{ translation_hash("Burst Epic Monster"), L"对大型野怪惩戒+Q" },
			{ translation_hash("Disco nunu"), L"开送" },
			{ translation_hash("BAN RISK 100%"), L"大几率封号" },
			{ translation_hash("go mid"), L"去中路" },
			{ translation_hash("spam chat"), L"狂刷聊天" },

			//Quinn
			{ translation_hash("Force E in R"), L"R时强制E" },
			{ translation_hash("Use Prowlers in combo"), L"连招中使用暗爪" },
			{ translation_hash("Use Harass When Mana Is Above in %"), L"魔法高于X的时候骚扰" },
			{ translation_hash("Use Spellfarm When Mana Is Above in %"), L"魔法高于X的时候用技能清线清野" },

			//rammus
			{ translation_hash("Semi Q"), L"手动热键Q" },
			{ translation_hash("Disable Evade on Q"), L"用Q的时候关躲避" },
			{ translation_hash("Insta E"), L"瞬间E" },
			{ translation_hash("Insta E on"), L"瞬间E敌人" },

			//Sej
			{ translation_hash("Q with prediction"), L"预判Q" },
			{ translation_hash("Q max range"), L"Q最大范围" },
			{ translation_hash("R Min Targets"), L"X个敌人及以上使用R" },
			{ translation_hash("Semi R"), L"手动热键R" },
			{ translation_hash("Use Q (mouse pos)"), L"Q鼠标中心" },

			//Shyvana
			{ translation_hash("if Target HP under mode"), L"如果目标生命低于" },
			{ translation_hash("Q On turret"), L"Q用在塔上" },
			{ translation_hash("Q On Wards"), L"Q眼" },
			{ translation_hash("Auto E"), L"自动E" },
			{ translation_hash("Immobile"), L"不移动" },
			{ translation_hash("Min minions Dragon form"), L"刷兵数量龙形态" },
			{ translation_hash("Min minions"), L"最少的兵" },

			//udyr
			{ translation_hash("Use Buff in:"), L"用buff" },
			{ translation_hash("Only W if my HP <=%"), L"只在我生命值低于X的时候用W" },
			{ translation_hash(" ^- %HP Incoming damage"), L"会打掉我X生命" },
			{ translation_hash("Always Force E if target stunnable"), L"如果敌人被晕强制E" },
			{ translation_hash("Only E in Selected Target"), L"只对选中的目标E" },
			{ translation_hash("Use Q before AA turret"), L"在打塔之前用Q" },
			{ translation_hash("Force W if my HP <=%"), L"如果我的生命低于X的时候强制W" },
			{ translation_hash("Use E2 in cc's"), L"对被控的敌人用E2" },
			{ translation_hash("Use E2 (buff)"), L"用带buff的E2" },


			{ translation_hash( "Side HUD" ), L"显示器" },
			{ translation_hash( "Size" ), L"大小" }, 
			{ translation_hash( "Notif" ), L"通知" },
			{ translation_hash( "Fake latency ping" ), L"假延迟ping" },
			{ translation_hash( "Send ping" ), L"发送ping" },
			{ translation_hash( "Fake latency" ), L"假延迟" },
			{ translation_hash( "Ping key" ), L"Ping键" },
			{ translation_hash( "Spell ready ping type" ), L"技能准备ping类型" },
			{ translation_hash( "Game ping" ), L"游戏ping" },
			{ translation_hash( "Chat message" ), L"聊天消息" },
			{ translation_hash( " ^ - Text" ), L" ^ - 文本" },
			{ translation_hash( "Spell cooldown ping type" ), L"技能冷却ping类型" },
			{ translation_hash( " - - Notify - - " ), L" - - 通知 - - " },
			{ translation_hash( "Surrender vote" ), L"投降投票" },
			{ translation_hash( "Use champion names" ), L"使用英雄名字" },
			{ translation_hash( "Jungle (in FoW)" ), L"丛林（战争迷雾中）" },
			{ translation_hash( "Small monster death" ), L"小怪物死亡" },
			{ translation_hash( "Big monster death" ), L"大怪物死亡" },
			{ translation_hash( "Objective attack" ), L"目标攻击" },
			{ translation_hash( "Auto ping" ), L"自动ping" },
			{ translation_hash( "Min delay" ), L"最小延迟" },
			{ translation_hash( "Max delay" ), L"最大延迟" },
			{ translation_hash( "Randomize position" ), L"随机化位置" },
			{ translation_hash( "Only on screen" ), L"仅在屏幕上" },
			{ translation_hash( "--Enemies( FoW ) - -" ), L"--敌人（战争迷雾）- -" },
			{ translation_hash( "Only jungler" ), L"只有打野" },
			{ translation_hash( " - - Objectives (FoW) - - " ), L" - - 目标（战争迷雾） - - " },
			{ translation_hash( "Traps" ), L"陷阱" },


			{ translation_hash( "Minimum reaction time (ms) for walking out" ), L"打到我x毫秒在走位躲避" },
			{ translation_hash( "Minimum reaction time (ms) to use spell to dodge" ), L"打到我x毫秒在用技能躲避" },
			{ translation_hash( "Dodge spells only if HP% <= X" ), L"躲技能生命低于x%" },
			{ translation_hash( "^ Igonore only dangerous if HP% <=" ), L"^ 生命 <= x% 时忽略" },
			



			//{ translation_hash(""), L"" },
			//{ translation_hash(""), L"" },

			});
	}
}